accounts/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("resetPasswordValidate/<uidb64>/<token>/", views.resetPasswordValidate, name="resetPasswordValidate"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("my_orders/", views.my_orders, name="my_orders"),
    path("change_password/", views.change_password, name="change_password"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("order_details/<int:order_id>", views.order_details, name="order_details"),
    path("forgotPassword/", views.forgotPassword, name="forgotPassword"),
    path("resetPassword/", views.resetPassword, name="resetPassword"),
    path("", views.dashboard, name="accounts"),
]

carts/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path("remove_cart/<int:product_id>/<int:cartItem_id>/", views.remove_cart, name="remove_cart"),
    path("remove_cart_item/<int:product_id>/<int:cartItem_id>", views.remove_cart_item, name="remove_cart_item"),
    path("checkout/", views.checkout, name="checkout"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="homepage"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include("accounts.urls")),
    path('orders/', include('orders.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.
class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError("Email Address is Required")
        if not username:
            raise ValueError("Username is Required")

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
         
        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
            password = password,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True

        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)

    # required
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    objects = MyAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'username']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True

class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address_line_1 = models.CharField(blank=True, max_length=100)
    address_line_2 = models.CharField(blank=True, max_length=100)
    profile_picture = models.ImageField(blank=True, upload_to="user_profile/")
    city = models.CharField(blank=True, max_length=50)
    state = models.CharField(blank=True, max_length=50)
    country = models.CharField(blank=True, max_length=50)

    def __str__(self):
        return self.user.first_name

    def full_address(self):
        return f"{self.address_line_1}, {self.address_line_2}"

accounts/forms.py
from django import forms
from .models import Account, UserProfile

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Enter Password",
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Confirm Password",
    }))

    class Meta:
        model = Account
        fields = ["first_name", "last_name", "phone_number", "email", "password"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs["placeholder"] = "Enter First Name"
        self.fields["last_name"].widget.attrs["placeholder"] = "Enter Last Name"
        self.fields["email"].widget.attrs["placeholder"] = "Enter Email"
        self.fields["phone_number"].widget.attrs["placeholder"] = "Enter Phone Number"
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control rounded-0"

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data["password"]
        confirm_password = cleaned_data["confirm_password"]

        if password != confirm_password:
            raise forms.ValidationError("Password doesn't match.")

        return cleaned_data

class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ["first_name", "last_name", "phone_number"]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control rounded-0"

class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages=
        {"invalid": "Image files only"}, widget=forms.FileInput()
    )
    
    class Meta:
        model = UserProfile
        fields = ["address_line_1", "address_line_2", "profile_picture", "city", "state", "country"]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control rounded-0"
        

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404

from .forms import RegistrationForm, UserForm, UserProfileForm
from .models import Account, UserProfile
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required

from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

from carts.models import Cart, CartItem
from carts.views import _cart_id, _check_equal

from orders.models import Order, OrderProduct

import requests

# Create your views here.
def register(request):
    form = RegistrationForm()

    if request.method == "POST":
        form = RegistrationForm(request.POST)

        if form.is_valid():
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            phone_number = form.cleaned_data["phone_number"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]

            username = email.split("@")[0]
            
            user = Account.objects.create_user(first_name, last_name, username, email, password)
            user.phone_number = phone_number
            user.save()

            mail_subject = "Please activate your account"
            current_site = get_current_site(request)
            context = {
                "user": user,
                "domain": current_site,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": default_token_generator.make_token(user),
            }
            message = render_to_string("accounts/account_verification_email.html", context)
            to_email = email
            send_mail = EmailMessage(mail_subject, message, to=[to_email])
            send_mail.send()

            return redirect("/accounts/login?command=verification")
        else:
            form = RegistrationForm(request.POST)

    data = {"form": form}
    return render(request, "accounts/register.html", context=data)

def login(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        user = auth.authenticate(email=email, password=password)
        if user:
            current_cart_id = _cart_id(request)
            if Cart.objects.filter(cart_id=current_cart_id).exists():
                current_cart = Cart.objects.get(cart_id=current_cart_id)
                items = CartItem.objects.filter(cart=current_cart)
            else:
                items = []

            auth.login(request, user)

            try:
                user_cart = Cart.objects.get(user=user)
                user_cart.cart_id = _cart_id(request)
            except:
                user_cart = Cart.objects.create(user=user, cart_id=_cart_id(request))

            user_items = CartItem.objects.filter(cart=user_cart)
            for item1 in items:
                itemAdded = False
                for item2 in user_items:
                    if item1.product == item2.product:
                        if _check_equal(item1.variations.all(), item2.variations.all()):
                            item2.quantity += item1.quantity
                            item2.save()
                            itemAdded = True
                            break
                if not itemAdded:
                    item1.cart = user_cart
                    item1.save()
            user_cart.save()

            try:
                url = request.META.get("HTTP_REFERER")
                queryString = requests.utils.urlparse(url).query
                queryDict = dict(x.split("=") for x in queryString.split("&"))
                if "next" in queryDict:
                    return redirect(queryDict["next"])
            except:
                return redirect("account:dashboard")
        else:
            messages.error(request, "Invalid Login Credentials.")

    return render(request, "accounts/login.html")

@login_required(login_url = "account:login")
def logout(request):
    auth.logout(request)
    messages.success(request, "You are logged out.")
    return redirect('account:login')

def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Congratulations, your account has been successfully created.")
        return redirect("account:login")
    
    else:
        messages.error(request, "Invalid activation link.")
        return redirect("account:register")

@login_required(login_url = "account:login")
def dashboard(request):
    profile_pic = ""

    user_profile = UserProfile.objects.filter(user=request.user)
    if user_profile:
        user_profile = user_profile[0]
        if user_profile.profile_picture:
            profile_pic = user_profile.profile_picture.url

    order_cnt = Order.objects.filter(user=request.user, is_ordered=True).count()

    context = {"order_cnt": order_cnt, "profile_pic": profile_pic}

    return render(request, "accounts/dashboard.html", context)

@login_required(login_url = "account:login")
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by("-created_at")

    context = {"orders": orders}

    return render(request, "accounts/my_orders.html", context)

login_required(login_url = "account:login")
def edit_profile(request):
    user_profile = UserProfile.objects.get_or_create(user=request.user)[0]

    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            messages.success(request, "Your profile has been updated.")
            return redirect("account:edit_profile")

    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=user_profile)

    context = {"user_form": user_form, "profile_form": profile_form}
    if user_profile.profile_picture:
        context["profile_pic"] = user_profile.profile_picture.url
        
    return render(request, "accounts/edit_profile.html", context)

login_required(login_url = "account:login")
def change_password(request):
    if request.method == "POST":
        current_password = request.POST["current_password"]
        new_password = request.POST["new_password"]
        confirm_password = request.POST["confirm_password"]

        user = auth.authenticate(email=request.user.email, password=current_password)
        if user:
            if new_password == confirm_password:
                user.set_password(new_password)
                user.save()
                auth.logout(request)
                messages.success(request, "Password changed successfully.")
                return redirect("account:login")
            else:
                messages.error(request, "The passwords don't match.")
        else:
            messages.error(request, "The password you entered is incorrect.")

    return render(request, "accounts/change_password.html")

login_required(login_url = "account:login")
def order_details(request, order_id):
    order = Order.objects.filter(order_number=order_id, user=request.user)
    context = {}

    if order:
        order = order[0]

        first_name = order.first_name
        last_name = order.last_name
        address_line_1 = order.address_line_1
        address_line_2 = order.address_line_2
        city = order.city
        state = order.state
        country = order.country

        ordered_products = OrderProduct.objects.filter(order=order, user=request.user)
        subtotal, tax = 0, 0
        for product in ordered_products:
            subtotal += product.product_price * product.quantity
        tax = 0.18 * subtotal

        payment = order.payment
        status = payment.status
        grand_total = payment.amount_paid

        context = {"first_name": first_name, "last_name": last_name, "address_line_1": address_line_1, "address_line_2": address_line_2, "city": city, "state": state, "country": country, "order_date": order.updated_at, "order_number": order_id, "payment_id": payment.payment_id, "status": status, "products": ordered_products, "subtotal": subtotal, "tax": tax, "grand_total": grand_total}

    return render(request, "accounts/order_details.html", context)

def forgotPassword(request):
    if request.method == "POST":
        email = request.POST["email"]
        if Account.objects.filter(email__exact=email).exists():
            user = Account.objects.get(email__exact=email)

            mail_subject = "Password Reset"
            current_site = get_current_site(request)
            context = {
                "user": user,
                "domain": current_site,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": default_token_generator.make_token(user),
            }
            message = render_to_string("accounts/reset_password_validate.html", context)
            to_email = email

templates/accounts/account_verification_email.html
{% autoescape off %}

Hello {{ user.first_name }},

You registered an account on "Ecommerce Website" before being able to use your account you need to verify that this is your email address by clicking here: http://{{ domain }}{% url 'account:activate' uidb64=uid token=token %}

Kind Regards, "Ecommerce Website"

{% endautoescape %}

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y">

    <div class="container">
        <div class="row">

            {% include 'includes/dashboard_sidebar.html' %}

            <main class="col-md-9">
                <article class="card">
                    <header class="card-header" style="background-color: black;">
                        <strong class="d-inline-block mr-3">Change Password:</strong>
                    </header>
                    <div class="card-body">
                        {% include 'includes/alerts.html' %}
                        <div class="row">
                            <div class="col-md-12">
                                <form action="" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group col-md-12">
                                        <label for="current_password">Current Password</label>
                                        <input type="password" name="current_password" id="current_password" class="form-control" required placeholder="Enter Current Password">
                                    </div>
                                    <div class="form-group col-md-12">
                                        <label for="new_password">New Password</label>
                                        <input type="password" name="new_password" id="new_password" class="form-control" required placeholder="Enter New Password">
                                    </div>
                                    <div class="form-group col-md-12">
                                        <label for="confirm_password">Confirm New Password</label>
                                        <input type="password" name="confirm_password" id="confirm_password" class="form-control" required placeholder="Confirm Password">
                                    </div>
                                    <button type="submit" class="btn btn-outline-danger">Submit</button>
                                </form>
                            </div>
                        </div> <!-- row.// -->
                    </div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y">

    <div class="container">
        <div class="row">

            {% include 'includes/dashboard_sidebar.html' %}

            <main class="col-md-9">
                <article class="card">
                    <header class="card-header" style="background-color: black">
                        <strong class="d-inline-block mr-3">Logged in as:</strong>
                        <span style="margin-left: -10px;">{{ user.first_name }} {{ user.last_name }}</span>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card" style="text-align: center;">
                                    <div class="card-body">
                                        <h5 class="card-title">Total Orders</h5>
                                        <h4>{{ order_cnt }}</h4>
                                        <a href="{% url 'account:my_orders' %}">View Orders</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="card" style="text-align: center;">
                                    <div class="card-body">
                                        <img src="{{ profile_pic }}" alt="" width="50" height="50" style="border-radius: 50%">
                                        <p class="mb-0 mt-1">{{ user.email }}</p>
                                        <p>{{ user.phone_number }}</p>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- row.// -->
                    </div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/forgot_password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

    <div class="card mx-auto " style="max-width: 380px; margin-top:100px;">
    <div class="card-body">
    <h4 class="card-title mb-4">Forgot Password</h4>
    {% include 'includes/alerts.html' %}
    <form action="{% url 'account:forgotPassword' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input name="email" type="email" class="form-control" placeholder="Email Address" >
        </div> <!-- form-group// -->
              
        <div class="form-group">
            <button type="submit" class="btn btn-outline-danger btn-block "> Submit  </button>
        </div> <!-- form-group// -->    
    </form>
    </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="{% url 'account:register' %}">Sign up</a></p>
    <br><br>

    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

    {% if request.GET.command == "verification" %}
      <div class="container mx-auto" style="max-width: 1000px; margin-top:100px;">
        <p class="alert alert-info" role="alert">Thanks for registering with us. We have sent a verification link to your email address. Please click on it to verify your account.
        <br><br>
        Already verified? <a href="{% url 'account:login' %}">Login</a>  
        </p>
      </div>

    {% else %}

        <div class="card mx-auto " style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          <h4 class="card-title mb-4">Sign in</h4>
          {% include 'includes/alerts.html' %}
          <form action="{% url 'account:login' %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                 <input name="email" type="email" class="form-control " placeholder="Email Address" >
              </div> <!-- form-group// -->
              <div class="form-group">
                <input name="password" type="password" class="form-control " placeholder="Password" >
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'account:forgotPassword' %}" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-outline-danger btn-block "> Login  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'account:register' %}">Sign up</a></p>
         <br><br>

    {% endif %}
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/my_orders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y">

    <div class="container">
        <div class="row">

            {% include 'includes/dashboard_sidebar.html' %}

            <main class="col-md-9">
                <article class="card">
                    <header class="card-header" style="background-color: black;">
                        <strong class="d-inline-block mr-3">Your Order History:</strong>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <table class="table table-hover">
                                <thead>
                                    <tr class="text-white">
                                        <th scope="col">Order #</th>
                                        <th scope="col">Billing Name</th>
                                        <th scope="col">Phone</th>
                                        <th scope="col">Order Total</th>
                                        <th scope="col">Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in orders %}
                                    <tr class="text-muted">
                                        <th scope="row">
                                            <a id="order-detail-link" href="{% url 'account:order_details' order_id=order.order_number %}">{{ order.order_number }}</a>
                                        </th>
                                        <td>{{ order.first_name }} {{ order.last_name }}</td>
                                        <td>{{ order.phone }}</td>
                                        <td>$ {{ order.order_total }}</td>
                                        <td>{{ order.created_at }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div> <!-- row.// -->
                    </div>


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/reset_password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->

    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
    <div class="card-body">
    <h4 class="card-title mb-4">Reset Password</h4>
    {% include 'includes/alerts.html' %}
    <form action="{% url 'account:resetPassword' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input name="password" type="password" class="form-control" placeholder="Enter Password" >
        </div> <!-- form-group// -->

        <div class="form-group">
            <input name="confirmPassword" type="password" class="form-control" placeholder="Confirm Password" >
        </div> <!-- form-group// -->
              
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
        </div> <!-- form-group// -->    
    </form>
    </div> <!-- card-body.// -->
    </div> <!-- card .// -->

    <p class="text-center mt-4">Don't have account? <a href="{% url 'account:register' %}">Sign up</a></p>
    <br><br>

    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/accounts/reset_password_validate.html
{% autoescape off %}

Hello {{ user.first_name }},

A request has been received to change the password for your account. Please click here to continue: http://{{ domain }}{% url 'account:resetPasswordValidate' uidb64=uid token=token %}

Kind Regards, "Ecommerce Website"

{% endautoescape %}