accounts/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("resetPasswordValidate/<uidb64>/<token>/", views.resetPasswordValidate, name="resetPasswordValidate"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("my_orders/", views.my_orders, name="my_orders"),
    path("change_password/", views.change_password, name="change_password"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("order_details/<int:order_id>", views.order_details, name="order_details"),
    path("forgotPassword/", views.forgotPassword, name="forgotPassword"),
    path("resetPassword/", views.resetPassword, name="resetPassword"),
    path("", views.dashboard, name="accounts"),
]

carts/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path("remove_cart/<int:product_id>/<int:cartItem_id>/", views.remove_cart, name="remove_cart"),
    path("remove_cart_item/<int:product_id>/<int:cartItem_id>", views.remove_cart_item, name="remove_cart_item"),
    path("checkout/", views.checkout, name="checkout"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="homepage"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include("accounts.urls")),
    path('orders/', include('orders.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path('', views.store, name="store"),
    path('category/<slug:category_slug>/', views.store, name="categorical_view"),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name="product_view"),
    path('search/', views.search, name="search"),
    path('submit_review/<int:product_id>/', views.submit_review, name="submit_review"),
] 

templates/includes/alerts.html
{% if messages %}
<div id="message" class="container">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
            {{ message }}
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/includes/dashboard_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group" id="sidebar">
        <a class="list-group-item {% if '/accounts/' == request.path or '/accounts/dashboard/' == request.path %}active{% endif %}" href="{% url 'account:dashboard' %}"> Dashboard </a>
        <a class="list-group-item {% if '/accounts/my_orders/' == request.path %}active{% endif %}" href="{% url 'account:my_orders' %}"> My Orders </a>
        <a class="list-group-item {% if '/accounts/edit_profile/' == request.path %}active{% endif %}" href="{% url 'account:edit_profile' %}"> Edit Profile </a>
        <a class="list-group-item {% if '/accounts/change_password/' == request.path %}active{% endif %}" href="{% url 'account:change_password' %}">Change Password </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'account:logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
    <!--   SIDEBAR .//END   -->
</aside>

templates/includes/footer.html
{% load static %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom row">
			<div class="col-md-2">
				<p class="text-white"> &copy 2019 Company name </p>
			</div>
			<div class="col-md-8 text-md-center text-muted">
				<span  class="px-2">info@pixsellz.io</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-white">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

templates/includes/navbar.html
{% load static %}
    
    <header class="section-header border-bottom" id="header">
        <a href="{% url 'homepage' %}" class="brand-wrap">
            <h1 style="color: red">E-Kart</h1>
        </a> <!-- brand-wrap.// -->
        <p id="toggle-navBar" style="font-size: 20px;">
            <i class="fa fa-bars" aria-hidden="true" style="color: red"></i>
        </p>
        <section class="header-main" id="navBar">
            <div class="container">
            <div class="row align-items-center">
            <div class="col-lg col-sm col-md col-6 flex-grow-0">
                <div class="category-wrap dropdown d-inline-block float-right">
                    <button type="button" class="btn btn-outline-danger dropdown-toggle " data-toggle="dropdown"> 
                        <i class="fa fa-bars"></i> All category 
                    </button>
                    <div class="dropdown-menu ">
                        {% for category in links %}
                            <a class="dropdown-item" href="{{ category.get_url }}">{{ category }}</a>
                        {% endfor %}
                    </div>
                </div>  <!-- category-wrap.// -->
            </div> <!-- col.// -->
            <a href="{% url 'store:store' %}" class="btn btn-outline-danger ">Store</a>
            <div class="col-lg  col-md-6 col-sm-12 col">
                <form action="{% url 'store:search' %}" class="search" method="get">
                    <div class="input-group w-100">
                        <input type="text" class="form-control input-text" style="width:60%; background: transparent; border: 1px solid red; color: white;" placeholder="Search" name="keyword">
                        
                        <div class="input-group-append">
                          <button class="btn btn-outline-danger " type="submit">
                            <i class="fa fa-search"></i>
                          </button>
                        </div>
                    </div>
                </form> <!-- search-wrap .end// -->
            </div> <!-- col.// -->
            <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                        <div class="d-flex justify-content-end mb-3 mb-lg-0">
                            {% if user.id is None %}
                            <div class="widget-header">
                                <small class="title text-white">Welcome guest!</small>
                                <div> 
                                    <a href="{% url 'account:login' %}">Sign in</a> <span class="dark-transp"> | </span>
                                    <a href="{% url 'account:register' %}"> Register</a>
                                </div>
                            </div>
                            {% else %}
                            <div class="widget-header">
                                <small class="title text-white">Welcome, {{ user.first_name }}</small>
                                <div> 
                                    <a href="{% url 'account:dashboard' %}">Dashboard</a>
                                    <span class="dark-transp"> | </span>
                                    <a href="{% url 'account:logout' %}">Logout</a>
                                </div>
                            </div>
                            {% endif %}
                            <a href="{% url 'cart:cart' %}" class="widget-header pl-3 ml-3">
                                <div class="icon icon-sm rounded-circle" id="cart" style="border: 1px solid red; color: red"><i class="fa fa-shopping-cart"></i></div>
                                <span class="badge badge-pill badge-danger notify" style="background: red">{{ items_count }}</span>
                            </a>
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
        </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->
        
    </header> <!-- section-header.// -->

    <script>
        const btn = document.getElementById("toggle-navBar");
        const navBar = document.getElementById("navBar");
        btn.addEventListener("click", () => {
            navBar.style.display = navBar.style.display == "" ? "block" : "";
        })
    </script>