carts/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path("remove_cart/<int:product_id>/<int:cartItem_id>/", views.remove_cart, name="remove_cart"),
    path("remove_cart_item/<int:product_id>/<int:cartItem_id>", views.remove_cart_item, name="remove_cart_item"),
    path("checkout/", views.checkout, name="checkout"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="homepage"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include("accounts.urls")),
    path('orders/', include('orders.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path("place_order", views.place_order, name="place_order"),
    path("payments", views.payments, name="payments"),
    path("order_complete", views.order_complete, name="order_complete"),
] 

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path('', views.store, name="store"),
    path('category/<slug:category_slug>/', views.store, name="categorical_view"),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name="product_view"),
    path('search/', views.search, name="search"),
    path('submit_review/<int:product_id>/', views.submit_review, name="submit_review"),
] 

carts/models.py
from django.db import models
from store.models import Product, Variation
from accounts.models import Account

# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.product_name

store/models.py
from unicodedata import category
from django.db import models
from django.urls import reverse
from category.models import Category
from accounts.models import Account
from django.db.models import Avg

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    images = models.ImageField(upload_to="photos/products")
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)
    modified_date = models.DateField(auto_now=True)

    def get_rating(self):
        ratings = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg("rating"))
        if ratings["average"]:
            return float("%.2f" % (ratings["average"] / len(ratings)))
        return 0

    def rating_cnt(self):
        ratings = ReviewRating.objects.filter(product=self, status=True)
        return len(ratings)

    def get_url(self):
        return reverse("store:product_view", kwargs={"category_slug": self.category.slug, "product_slug": self.slug})

    def __str__(self):
        return self.product_name

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category="color", is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category="size", is_active=True)

variation_category_choices = (
    ("size", "size"),
    ("color", "color"),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choices)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.TimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.subject

class ProductGallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="store/products/")

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = "product gallery"
        verbose_name_plural = "product gallery"


store/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ["subject", "review", "rating"]

carts/views.py
from typing import Counter
from django.http import HttpResponse, QueryDict
from django.shortcuts import get_object_or_404, redirect, render

from django.contrib.auth.decorators import login_required

from .models import Cart, CartItem
from store.models import Product, Variation

def _check_equal(q1, q2):
    return Counter(q1) == Counter(q2)

# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    product_variations = []

    if request.method == "POST":
        for key in request.POST:
            value = request.POST[key]

            try:
                variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                product_variations.append(variation)
            except:
                pass


    product = Product.objects.get(id=product_id) 

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )

    cart.save()
    
    cartItem = None
    itemExists = CartItem.objects.filter(product=product, cart=cart).exists()
    if itemExists:
        cartItems = CartItem.objects.filter(product=product, cart=cart)

        for item in cartItems:
            q1, q2 = list(item.variations.all()), product_variations
            if _check_equal(q1, q2):
                cartItem = item
        
        if cartItem:
            cartItem.quantity += 1
        
    if not cartItem:
        cartItem = CartItem.objects.create(product=product, cart=cart, quantity=1)

        if len(product_variations) > 0:
            cartItem.variations.clear()
            for item in product_variations:
                cartItem.variations.add(item)
    
    cartItem.save()
    
    return redirect('cart:cart')

def remove_cart(request, product_id, cartItem_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    
    try:
        cartItem = CartItem.objects.get(product=product, cart=cart, id=cartItem_id)

        if cartItem.quantity > 1:
            cartItem.quantity -= 1
            cartItem.save()
        else:
            cartItem.delete()

    except:
        pass

    return redirect('cart:cart')

def remove_cart_item(request, product_id, cartItem_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    
    try:
        cartItem = CartItem.objects.get(product=product, cart=cart, id=cartItem_id)

        cartItem.delete()
    except:
        pass

    return redirect('cart:cart')

def cart(request):
    items, price, tax, grand_price, quantity = [], 0, 0, 0, 0
    
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        items = CartItem.objects.filter(cart=cart, is_active=True)
        for item in items:
            price += item.product.price * item.quantity
            quantity += item.quantity
        tax = (18 * price) / 100
        grand_price = price + tax
    except Cart.DoesNotExist:
        pass
    
    grand_price = "{:,}".format(grand_price)
    price = "{:,}".format(price)
    
    data = {"items": items, "price": price, "tax": tax, "grand_price": grand_price, "quantity": quantity}

    return render(request, "store/cart.html", context=data)

@login_required(login_url="account:login")
def checkout(request):
    items, price, tax, grand_price, quantity = [], 0, 0, 0, 0
    
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        items = CartItem.objects.filter(cart=cart, is_active=True)
        for item in items:
            price += item.product.price * item.quantity
            quantity += item.quantity
        tax = (18 * price) / 100
        grand_price = price + tax
    except Cart.DoesNotExist:
        pass
    
    grand_price = "{:,}".format(grand_price)
    price = "{:,}".format(price)
    
    data = {"items": items, "price": price, "tax": tax, "grand_price": grand_price, "quantity": quantity}

    return render(request, "store/checkout.html", data)

store/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Product, ProductGallery, ReviewRating
from category.models import Category
from django.http import Http404
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import ReviewForm
from django.contrib import messages
from orders.models import OrderProduct

# Create your views here.
def store(request, category_slug=None):

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.all().filter(category=category, is_available=True).order_by("id")
        count = products.count()

        paginator = Paginator(products, 1)
        page = request.GET.get("page")
        products = paginator.get_page(page)
    else:
        products = Product.objects.all().filter(is_available=True).order_by("id")
        count = products.count()

        paginator = Paginator(products, 6)
        page = request.GET.get("page")
        products = paginator.get_page(page)

    data = {"products": products, "count": count}

    return render(request, "store/store.html", context=data)

def product_detail(request, category_slug=None, product_slug=None):
    data = {"purchased": False}

    if product_slug and category_slug:
        product =  get_object_or_404(Product, slug=product_slug, category__slug=category_slug)
        data["photos"] = ProductGallery.objects.filter(product=product)
        data["product"] = product
        data["reviews"] = ReviewRating.objects.filter(product=product, status=True).order_by("-created_at")

        purchased = False
        if request.user.is_authenticated:
            purchasedProducts = OrderProduct.objects.filter(user=request.user, product=product)

            for product in purchasedProducts:
                if product.payment.status == "COMPLETED":
                    purchased = True
                    break
        data["purchased"] = purchased

    return render(request, "store/product_detail.html", context=data)

def search(request):
    query = request.GET.get("keyword")

    if query:
        products = Product.objects.filter(Q(product_name__icontains=query) | Q(description__icontains=query))
        count = products.count()
    else:
        products = []
        count = 0

    data = {"products": products, "count": count}

    return render(request, "store/store.html", context=data)

@login_required(login_url = "account:login")
def submit_review(request, product_id):
    if request.method == "POST":
        form = ReviewForm(request.POST)

        if form.is_valid():
            product = Product.objects.get(id=product_id)
            rating = form.cleaned_data["rating"]
            subject = form.cleaned_data["subject"]
            review = form.cleaned_data["review"]
            ip = request.META.get('REMOTE_ADDR')

            try:
                review_object = ReviewRating.objects.get(user=request.user, product=product)
            except:
                review_object = ReviewRating()
                review_object.user = request.user
                review_object.product = product

            review_object.rating = rating
            review_object.subject = subject
            review_object.review = review
            review_object.ip = ip
            review_object.save()

            messages.success(request, "Thanks for your review.")
        
        else:
            messages.error(request, "Oops. You might have missed something.")

    return redirect(request.META.get('HTTP_REFERER'))

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not items %}

	<h2 class="text-center text-muted">Your Shopping Cart is Empty!</h1>
	<br>	
	<div class="text-center">
		<a href="{% url 'store:store' %}">
			<button class="btn btn-light">Continue Shopping</button>
		</a>
	</div>

{% else %}	

<div class="row">
	<aside class="col-lg-9">
<div class="card ">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for item in items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ item.product.images.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ item.product.get_url }}" class="title text-white">{{ item.product.product_name }}</a>
				<p class="text-muted small">
					{% for variation in item.variations.all %}
						{{ variation.variation_category | capfirst }}
						:
						{{ variation.variation_value | capfirst }}
						<br>
					{% endfor %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td> 
		<!-- col.// -->
					<div class="col"> 
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'cart:remove_cart' product_id=item.product.id cartItem_id=item.id %}">
								<button class="btn btn-light " type="button" id="button-minus"> <i class="fa fa-minus" style="color: grey"></i> </button>
							</a>
							</div>
							<input type="text" class="form-control"  value="{{ item.quantity }}">
							<div class="input-group-append">
								<form action="{% url 'cart:add_cart' product_id=item.product.id %}" method="post">
									{% csrf_token %}
									{% for variation in item.variations.all %}
										<input type="hidden" name="{{ variation.variation_category | lower}}" value="{{variation.variation_value | lower }}">
									{% endfor %}

									<button class="btn btn-light " type="submit" id="button-plus"> <i class="fa fa-plus" style="color: grey"></i> </button>
								</form>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td> 
		<div class="price-wrap"> 
			<var class="price text-muted">$ {{ item.sub_total }}</var> 
			<small class="text-muted"> $ {{ item.product.price }} each </small> 
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right"> 
	<a href="{% url 'cart:remove_cart_item' product_id=item.product.id cartItem_id=item.id %}" class="btn btn-danger "> Remove</a>
	</td>
</tr>
{% endfor %}

</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->

	<aside class="col-lg-3">

		<div class="card ">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">$ {{ price }}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> $ {{ tax }} </dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-muted b"><strong>$ {{ grand_price }}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static 'images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'cart:checkout' %}" class="btn btn-outline-danger btn-block "> Checkout </a>
			<a href="./store.html" class="btn btn-light btn-block" style="color: black">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->

{% endif %}

<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y">
	<div class="container">

		<!-- ============================ COMPONENT 1 ================================= -->	
		<div class="card ">
			<div class="row no-gutters">
				<aside class="col-md-6">
					<article class="gallery-wrap">
						<div class="img-big-wrap">
							<a href="#"><img src="{{ product.images.url }}"></a>
						</div> <!-- img-big-wrap.// -->
					</article> <!-- gallery-wrap .end// -->
					<ul class="product-thumbnail">
						<li class="rounded">
							<img src="{{ product.images.url }}">
						</li>
						{% for photo in photos %}
						<li class="rounded">
							<img src="{{ photo.image.url }}">
						</li>
						{% endfor %}
					</ul>
				</aside>
				<main class="col-md-6 border-left">

					<form action="{% url 'cart:add_cart' product_id=product.id %}" method="POST">
						{% csrf_token %}
						<article class="content-body">

							<h2 class="title">{{ product.product_name }}</h2>
							
							{% if product.get_rating != 0 %}
								<div class="rating" style="margin-bottom: 15px; color: orange;">
									<i class="fa fa-star{% if product.get_rating < 0.5 %}-o{% elif product.get_rating < 1 %}-half-o{% endif %}"></i>
									<i class="fa fa-star{% if product.get_rating < 1.5 %}-o{% elif product.get_rating < 2 %}-half-o{% endif %}"></i>
									<i class="fa fa-star{% if product.get_rating < 2.5 %}-o{% elif product.get_rating < 3 %}-half-o{% endif %}"></i>
									<i class="fa fa-star{% if product.get_rating < 3.5 %}-o{% elif product.get_rating < 4 %}-half-o{% endif %}"></i>
									<i class="fa fa-star{% if product.get_rating < 4.5 %}-o{% elif product.get_rating < 5 %}-half-o{% endif %}"></i>
									&nbsp;
									<span style="color: rgb(100, 100, 100)">{{ product.rating_cnt }} rating{% if product.rating_cnt > 1 %}s{% endif %}</span>
								</div>
							{% endif %}

							<div class="mb-3">
								<var class="price h4 text-white">$ {{ product.price }}</var>
							</div>

							<p>{{ product.description }}</p>


							<hr>
							<div class="row">
								&nbsp;&nbsp;
								<div class="item-option-select" required>
									<h6>Choose Color</h6>
									<select name="color" class="form-control" required>
										<option value="" disabled selected>Select</option>
										{% for var in product.variation_set.colors %}
										<option value="{{ var.variation_value | lower }}">{{ var.variation_value |capfirst }}</option>
										{% endfor %}
									</select>
								</div>
							</div> <!-- row.// -->
							<div class="row">
								&nbsp;&nbsp;
								<div class="item-option-select">
									<h6>Select Size</h6>
									<select name="size" class="form-control ">
										<option value="" disabled selected>Select</option>
										{% for var in product.variation_set.sizes %}
										<option value="{{ var.variation_value | lower }}">{{ var.variation_value | capfirst }}</option>
										{% endfor %}
									</select>
								</div>
							</div> <!-- row.// -->
							<hr>
							{% if product.stock > 0 %}
							<button type="submit" class="btn btn-outline-danger"> <span class="text">Add to cart</span> <i
									class="fas fa-shopping-cart"></i></button>
							{% else %}
							<btn class="btn btn-danger ">Out of Stock</btn>
							{% endif %}

						</article> <!-- product-info-aside .// -->
					</form>

				</main> <!-- col.// -->
			</div> <!-- row.// -->
		</div> <!-- card.// -->
		<!-- ============================ COMPONENT 1 END .// ================================= -->

		<br>

		<div class="row">
			<div class="col-md-9">

				<header class="section-heading">
					<h3 class="text-white">Customer Reviews </h3>
				</header>

				{% if product.get_rating != 0 %}
					<div class="rating" style="margin-bottom: 25px; color: orange;">
						<i class="fa fa-star{% if product.get_rating < 0.5 %}-o{% elif product.get_rating < 1 %}-half-o{% endif %}"></i>
						<i class="fa fa-star{% if product.get_rating < 1.5 %}-o{% elif product.get_rating < 2 %}-half-o{% endif %}"></i>
						<i class="fa fa-star{% if product.get_rating < 2.5 %}-o{% elif product.get_rating < 3 %}-half-o{% endif %}"></i>
						<i class="fa fa-star{% if product.get_rating < 3.5 %}-o{% elif product.get_rating < 4 %}-half-o{% endif %}"></i>
						<i class="fa fa-star{% if product.get_rating < 4.5 %}-o{% elif product.get_rating < 5 %}-half-o{% endif %}"></i>
						&nbsp;
						<span style="color: black;">{{ product.get_rating }} out of 5</span>
						<br>
						<span style="color: rgb(100, 100, 100)">{{ product.rating_cnt }} rating{% if product.rating_cnt > 1 %}s{% endif %}</span>
					</div>
				{% endif %}

					<div class="card ">
						<form action="{% url 'store:submit_review' product.id %}" method="POST">
						{% csrf_token %}
						{% include 'includes/alerts.html' %}
						<h5 class="card-header" style="background-color: black; overflow: none">Review this Product</h5>
						<div class="card-body">
							<div class="form-group rate">
								<input type="radio" name="rating" id="ratingBtn10" value="5"><label for="ratingBtn10" title="5"></label>
								<input type="radio" name="rating" id="ratingBtn9" value="4.5"><label for="ratingBtn9" title="4.5" class="half"></label>
								<input type="radio" name="rating" id="ratingBtn8" value="4"><label for="ratingBtn8" title="4"></label>
								<input type="radio" name="rating" id="ratingBtn7" value="3.5"><label for="ratingBtn7" title="3.5" class="half"></label>
								<input type="radio" name="rating" id="ratingBtn6" value="3"><label for="ratingBtn6" title="3"></label>
								<input type="radio" name="rating" id="ratingBtn5" value="2.5"><label for="ratingBtn5" title="2.5"  class="half"></label>
								<input type="radio" name="rating" id="ratingBtn4" value="2"><label for="ratingBtn4" title="2"></label>
								<input type="radio" name="rating" id="ratingBtn3" value="1.5"><label for="ratingBtn3" title="1.5"  class="half"></label>
								<input type="radio" name="rating" id="ratingBtn2" value="1"><label for="ratingBtn2" title="1"></label>
								<input type="radio" name="rating" id="ratingBtn1" value="0.5"><label for="ratingBtn1" title="0.5"  class="half"></label>
							</div>
							<div class="form-group">
								<label for="subject">Review Title:</label>
								<input type="text" class="form-control " name="subject" id="subject">
							</div>
							<div class="form-group">
								<label for="review">Review Description:</label>
								<textarea name="review" id="review" cols="30" rows="4" class="form-control "></textarea>
							</div>
							{% if user.is_authenticated %}
								{% if purchased %}
									<button type="submit" class="btn btn-outline-danger ">Submit Review</button>
								{% else %}
									<a class="btn btn-danger " style="color: white;">Not Allowed</a>
								{% endif %}
							{% else %}
								<a class="btn btn-danger " style="color: white;">Login Required</a>
							{% endif %}
						</div>
						</form>
					</div>

				<br>

				{% for review in reviews %}
					<article class="box mb-3 " style="background-color: black; color: white; border: 1px solid red">
						<div class="icontext w-100">
							<img src="{% static './images/avatars/default.jpg' %}" class="img-xs icon rounded-circle">
							<div class="text">
								<span class="date text-muted float-md-right">{{ review.updated_at }} </span>
								<h6 class="mb-1 text-muted">{{ review.user.first_name }} {{ review.user.last_name }}</h6>
							</div>
						</div> <!-- icontext.// -->

						<div class="mt-3">
							<span>
								<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o{% endif %}" style="color: orange;"></i>
								<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o{% endif %}"style="color: orange;"></i>
								<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o{% endif %}"style="color: orange;"></i>
								<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o{% endif %}"style="color: orange;"></i>
								<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o{% endif %}"style="color: orange;"></i>
							</span>
							&nbsp;
							<h6 style="display: inline-block;">
								{{ review.subject}}
							</h6>
							<p>
								{{ review.review }}
							</p>
						</div>
					</article>
				{% endfor %}



			</div> <!-- col.// -->
		</div> <!-- row.// -->


	</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

{% block scripts %}
<script>
	var mainImageContainer = document.getElementsByClassName("img-big-wrap")[0];
	var thumbnailParent = document.getElementsByClassName("product-thumbnail")[0];
	var thumbnails = thumbnailParent.querySelectorAll("li");
	thumbnails.forEach(thumbnail => {
		thumbnail.addEventListener("click", function(){
			var imgSource = thumbnail.querySelector("img").getAttribute("src");
			mainImageContainer.querySelector("img").setAttribute("src", imgSource);
		})
	});
</script>
{% endblock %}