carts/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path("", views.cart, name="cart"),
    path("add_cart/<int:product_id>/", views.add_cart, name="add_cart"),
    path("remove_cart/<int:product_id>/<int:cartItem_id>/", views.remove_cart, name="remove_cart"),
    path("remove_cart_item/<int:product_id>/<int:cartItem_id>", views.remove_cart_item, name="remove_cart_item"),
    path("checkout/", views.checkout, name="checkout"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="homepage"),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include("accounts.urls")),
    path('orders/', include('orders.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path("place_order", views.place_order, name="place_order"),
    path("payments", views.payments, name="payments"),
    path("order_complete", views.order_complete, name="order_complete"),
] 

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path('', views.store, name="store"),
    path('category/<slug:category_slug>/', views.store, name="categorical_view"),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name="product_view"),
    path('search/', views.search, name="search"),
    path('submit_review/<int:product_id>/', views.submit_review, name="submit_review"),
] 

orders/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, Variation

# Create your models here.
class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(unique=True, max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.FloatField()
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id

class Order(models.Model):
    STATUS = (
        ("New", "New"),
        ("Accepted", "Accepted"),
        ("Completed", "Completed"),
        ("Cancelled", "Cancelled"),
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, null=True)
    order_number = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=50)
    address_line_2 = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default="New")
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.order_number

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

orders/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["first_name", "last_name", "phone", "email", "address_line_1", "address_line_2", "country", "state", "city", "order_note"]

orders/views.py
import json
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import JsonResponse

from carts.models import Cart
from carts.views import _cart_id
from carts.models import CartItem

from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.core.mail import EmailMessage

from .forms import OrderForm
from .models import Order, OrderProduct, Payment

import datetime

from carts.views import _check_equal

import time

# Create your views here.
@login_required(login_url="account:login")
def place_order(request):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    cartItems = CartItem.objects.filter(cart=cart)
    if cartItems.exists(): 
        price, grand_price, tax, quantity = 0, 0, 0, 0
        for item in cartItems:
            price += item.product.price * item.quantity
            quantity += item.quantity
        tax = (18 * price) / 100
        grand_price = price + tax

        if request.method == "POST":
            form = OrderForm(request.POST)
            if form.is_valid():
                order = Order()
                order.user = request.user
                order.first_name = form.cleaned_data["first_name"]
                order.last_name = form.cleaned_data["last_name"]
                order.phone = form.cleaned_data["phone"]
                order.email = form.cleaned_data["email"]
                order.address_line_1 = form.cleaned_data["address_line_1"]
                order.address_line_2 = form.cleaned_data["address_line_2"]
                order.country = form.cleaned_data["country"]
                order.state = form.cleaned_data["state"]
                order.city = form.cleaned_data["city"]
                order.order_note = form.cleaned_data["order_note"]
                order.order_total = grand_price
                order.tax = tax
                order.ip = request.META.get('REMOTE_ADDR')
                order.save()

                yr = datetime.date.today().year
                dt = datetime.date.today().day
                mt = datetime.date.today().month
                d = datetime.date(yr, mt, dt)
                current_date = d.strftime("%Y%m%d")
                order_number = current_date + str(order.id)
                order.order_number = order_number
                order.save()

                orderedProducts = []
                for item in cartItems:
                    orderedProduct = OrderProduct(
                        order = order,
                        user = request.user,
                        product = item.product,
                        quantity = item.quantity,
                        product_price = item.sub_total()
                    )
                    orderedProduct.save()
                    for variation in item.variations.all():
                        orderedProduct.variations.add(variation)
                    orderedProduct.save()
                    orderedProducts.append(orderedProduct)

                context = {
                    "order": Order.objects.get(user=request.user, order_number=order_number, is_ordered=False),
                    "cart_items": orderedProducts,
                    "price": price, 
                    "grand_price": grand_price, 
                    "tax": tax, 
                    "quantity": quantity,
                }
                return render(request, "orders/payments.html", context)

    return redirect("store:store")

@login_required(login_url="account:login")
def payments(request):
    body = json.loads(request.body)
    
    order = Order.objects.get(user=request.user, order_number=body["orderID"], is_ordered=False)

    payment = Payment(
        user = request.user,
        payment_id = body["transID"],
        payment_method = body["paymentMethod"],
        amount_paid = order.order_total,
        status = body["status"]
    )
    payment.save()

    order.payment = payment
    order.is_ordered = True
    order.save()

    orderedProducts = OrderProduct.objects.filter(order=order, user=request.user, is_ordered=False)
    for orderedProduct in orderedProducts:
        orderedProduct.payment = payment
        orderedProduct.is_ordered = True
        orderedProduct.save()

    cart = Cart.objects.get(cart_id=_cart_id(request))
    for orderedProduct in orderedProducts:
        product = orderedProduct.product
        cartItems = CartItem.objects.filter(cart=cart, product=product)
        for item in cartItems:
            if _check_equal(item.variations.all(), orderedProduct.variations.all()):
                item.quantity -= orderedProduct.quantity
                item.save()
                if item.quantity <= 0: item.delete()
                break
        product.stock -= orderedProduct.quantity
        product.save()

    mail_subject = "Order Confirmation"
    context = {
        "user": order.user,
        "order": order,
    }
    message = render_to_string("orders/order_confirmation_email.html", context)
    to_email = order.email
    send_email = EmailMessage(mail_subject, message, to=[to_email,])
    send_email.send()

    data = {
        "order_number": order.order_number,
        "payment_id": body["transID"],
    }
    return JsonResponse(data)

def order_complete(request):
    order_number = request.GET.get("order_number")
    payment_id = request.GET.get("payment_id")
    
    order = Order.objects.get(order_number=order_number, user=request.user)
    first_name = order.first_name
    last_name = order.last_name
    address_line_1 = order.address_line_1
    address_line_2 = order.address_line_2
    city = order.city
    state = order.state
    country = order.country
    
    now = datetime.datetime.now()
    dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
    order_date = dt_string.replace(" ", ", ")

    ordered_products = OrderProduct.objects.filter(order=order, user=request.user)
    subtotal, tax = 0, 0
    for product in ordered_products:
        subtotal += product.product_price * product.quantity
    tax = 0.18 * subtotal

    payment = Payment.objects.get(payment_id=payment_id, user=request.user)
    status = payment.status
    grand_total = payment.amount_paid

    context = {"first_name": first_name, "last_name": last_name, "address_line_1": address_line_1, "address_line_2": address_line_2, "city": city, "state": state, "country": country, "order_date": order_date, "order_number": order_number, "payment_id": payment_id, "status": status, "products": ordered_products, "subtotal": subtotal, "tax": tax, "grand_total": grand_total}
    return render(request, "orders/order_complete.html", context)

templates/orders/order_complete.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container" style="margin-top: 50px;">
    <center><i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></center>
    <h2 class="text-center">Payment Successful</h2>
	<br>
	<div class="text-center">
		<a href="{% url 'store:store' %}" class="btn btn-success">Shop more</a>
	</div>
</div>

<div class="container" style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
    <div class="row invoice row-printable">
        <div class="col-md-12">
            <!-- col-lg-12 start here -->
            <div class="panel panel-default plain" id="dash_0">
                <!-- Start .panel -->
                <div class="panel-body p30">
                    <div class="row">
                        <!-- Start .row -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-logo"><img src="{% static '/images/logo.png' %}" alt="Invoice logo" style="max-height: 40px;"></div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-from">
                                <ul class="list-unstyled text-right">
                                    <li><strong>Invoiced To</strong></li>
                                    <li>{{ first_name }} {{ last_name }}</li>
                                    <li>{{ address_line_1 }}, {{ address_line_2 }}</li>
                                    <li>{{ city }}, {{ state }}</li>
                                    <li>{{ country }}</li>
                                </ul>
                            </div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <div class="invoice-details mt25">
                                <div class="well">
                                    <ul class="list-unstyled mb0">
                                        <li><strong>Order</strong> #{{ order_number }}</li>
                                        <li><strong>Transaction</strong> #{{ payment_id }}</li>
                                        <li><strong>Order Date:</strong> {{ order_date }}</li>
                                        <li><strong>Status:</strong> {{ status }}</li>
                                    </ul>
                                </div>
                            </div>
                           
                            <div class="invoice-items">
                                <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="per70 text-center">Description</th>
                                                <th class="per5 text-center">Qty</th>
                                                <th class="per25 text-center">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for product in products %}
                                            <tr>
                                                <td>{{ product.product }}<br>
                                                {% for variation in product.variations.all %}
                                                    {{ variation.variation_category | capfirst }}
                                                    :
                                                    {{ variation.variation_value | capfirst }}
                                                    <br>
                                                {% endfor %}
                                                </td>
                                                <td class="text-center">{{ product.quantity }}</td>
                                                <td class="text-center">$ {{ product.product_price }}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th colspan="2" class="text-right">Sub Total:</th>
                                                <th class="text-center">$ {{ subtotal }}</th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" class="text-right">Tax:</th>
                                                <th class="text-center">$ {{ tax }}</th>
                                            </tr>
                                            
                                            <tr>
                                                <th colspan="2" class="text-right">Grand Total:</th>
                                                <th class="text-center">$ {{ grand_total }}</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div class="invoice-footer mt25">
                                <p class="text-center">Thank you for shopping with us!</p>
                            </div>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                    <!-- End .row -->
                </div>
            </div>
            <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
    </div>
    </div>
{% endblock %}

templates/orders/order_confirmation_email.html
{% autoescape off %}

Hello {{ user.first_name }},

Your Order No. {{ order.order_number }}, dated at {{ order.created_at }} has been recieved. We will keep you updated for the same! Thanks for shopping with us!

Kind Regards, "Ecommerce Website"

{% endautoescape %}

templates/orders/payments.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="section-content padding-y">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->

        <h4 class="ml-3 mb-3 text-white">Review your Order</h4>
        <div class="row">
            <aside class="col-lg-8">
                <div class="card">
                    <h5 class="card-header" style="background-color: black">Billing Address</h5>
                    <div class="card-body">
                        <p class="card-text">
                            {{ order.first_name }} {{ order.last_name }}<br>
                            {{ order.address_line_1 }}, {{ order.address_line_2 }}<br>
                            {{ order.city }}, {{ order.state }}<br>
                            {{ order.country }}<br>
                            {{ order.email }}<br>
                            {{ order.phone }}
                        </p>
                        {% if order.order_note %}
                        <p>
                            <b>Order Note: </b>{{ order.order_note }}
                        </p>
                        {% endif %}
                    </div>
                </div>
                <br>
                <div class="card">
                    <h5 class="card-header" style="background-color: black">Payment Method</h5>
                    <div class="card-body">
                        <p class="card-text">PayPal</p>
                    </div>
                </div>
                <br>
                <div class="card">
                    <h5 class="card-header" style="background-color: black">Review Products</h5>
                    <div class="card-body">
                        <div class="card">
                            <div class="card-body">
                                <table class="table table-borderless table-shopping-cart">
                                    <thead class="text-muted">
                                        <tr class="small text-uppercase">
                                            <th scope="col">Product</th>
                                            <th scope="col" width="200">Quantity</th>
                                            <th scope="col" width="120">Price</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in cart_items %}
                                        <tr>
                                            <td>
                                                <figure class="itemside align-items-center">
                                                    <div class="aside"><img src="{{ item.product.images.url }}"
                                                            class="img-sm"></div>
                                                    <figcaption class="info">
                                                        <a href="{{ item.product.get_url }}" class="title text-muted">{{ item.product.product_name }}</a>
                                                        <p class="text-muted small">
                                                            {% for variation in item.variations.all %}
                                                            {{ variation.variation_category | capfirst }}
                                                            :
                                                            {{ variation.variation_value | capfirst }}
                                                            <br>
                                                            {% endfor %}
                                                        </p>
                                                    </figcaption>
                                                </figure>
                                            </td>
                                            <td>
                                                <label for="" class="text-muted">{{ item.quantity }}</label>
                                            </td>
                                            <td>
                                                <div class="price-wrap">
                                                    <var class="price text-muted">$ {{ item.product_price }}</var>
                                                    <small class="text-muted"> $ {{ item.product.price }} each </small>
                                                </div> <!-- price-wrap .// -->
                                            </td>
                                        </tr>
                                        {% endfor %}

                                    </tbody>
                                </table>
                            </div> <!-- card-body.// -->
                        </div> <!-- card.// -->
                    </div>
                </div>

            </aside> <!-- col.// -->

            <aside class="col-lg-4">

                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">$ {{ price }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right"> $ {{ tax }} </dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Total:</dt>
                            <dd class="text-right text-muted b"><strong>$ {{ grand_price }}</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="{% static 'images/misc/payments.png' %}" height="26">
                        </p>

                        <div id="paypal-button-container">

                        </div>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->

            </aside> <!-- col.// -->


        </div> <!-- row.// -->

        <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    var amount = "{{ grand_price }}";
    var order_number = "{{ order.order_number }}";
    var url = "{% url 'order:payments' %}";
    var payment_method = "PayPal";
    var redirect_url = "{% url 'order:order_complete' %}"

    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        style: {
            color: 'blue',
            shape: 'rect',
            label: 'pay',
            height: 40
        },

        // Set up the transaction
        createOrder: function (data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: amount,
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function (data, actions) {
            return actions.order.capture().then(function (orderData) {
                sendData();

                function sendData(){
                    fetch(url, {
                        method: "POST",
                        headers: {
                            "Content-type": "application/json",
                            "X-CSRFToken": csrftoken, 
                        },
                        body: JSON.stringify({
                            orderID: order_number,
                            transID: orderData.id,
                            paymentMethod: payment_method,
                            status: orderData.status,
                        }),
                    })
                    .then((response) => response.json())
                    .then((data) => {
                        window.location.href = redirect_url + '?order_number=' + data.order_number + '&payment_id=' + data.payment_id;
                    })
                }
            });
        }


    }).render('#paypal-button-container');
</script>

{% endblock %}